import random

wins_moriarty = 0 #the number of wins by Moriarty. We could also explicitly make a variable for Holme's victories, but it's not required by the exercise
for i in range(0,100000): #we simulate 100,000 rounds 
    s = 0 #we initialize s to 0 at every round
    while s < 100: #condition necessary for the player to change (exits when s is more than 100)
        x = random.randint(1,100) #generate random integer from 1 to 100
        s = s + x #add it to s
    sherlock = x #save x for later use (could directly use x without declaring another variable, but I think this makes the logic of the program clearer)
    while s < 200: #condition necessary to finish the game (exits when s is more than 200)
        y = random.randint(1,100) #generate a random ineteger between 1 and 100
        s = s + y #add the random number to s
    moriarty = y #save y for later use (the same as with sherlock)
    if sherlock < moriarty: #if the last random number generated by sherlock is less than the one generated by moriarty, we give the victory to this last one. As the draw case was not made explicit in the assignment, we have decided to give the win to moriarty if such a case arises.
        wins_moriarty = wins_moriarty + 1 #we update moriarty's victory count
print("Moriarty's win rate: ", str(wins_moriarty/100000)) #we print moriarty's win percentage, as requested
    
